name: SonarQube Analysis (Manual Project) added

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SonarQube Scanner
        uses: SonarSource/sonar-scanner-action@main
        with:
          args: >
            -Dsonar.projectKey=linux-sonar-30mil
            -Dsonar.sources=.
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

